### ISSUE TITLE
Add a `mv` command to move an existing clone to the "correct" path.

### ISSUE THREAD

**Issue by jmalloc** [jmalloc/grit#1]
Not technically blocked, but makes sense to finish #3 first.

- `grit mv` - moves the current clone to the standard `clone.root` location
- `grit mv --golang` - equivalent for `$GOPATH/src`

**Comment by jmalloc** [comment]
Maybe `move --go` or similar. FYI @koden-km

**Comment by koden-km** [comment]
Yeah `move` with optional sounds good. Then it can move a cloned repo from anywhere to your "standard" location, which will be good for moving from custom manual clones to grit managed. eg. `~/Documents/Projects/foo` to `~/grit/github.com/dudeguy/foo`.

**Comment by jmalloc** [comment]
Yeah that sounds good actually. I'll update the title to match.

**Comment by jmalloc** [comment]
If there are multiple possible matches, favour the URL from `origin`.
