### ISSUE TITLE
Add `self-update` command

### ISSUE THREAD

**Issue by jmalloc** [jmalloc/grit#14]
- find latest release via github API
- download archive and unpack, replace current binary
- signing / verification?
- rollback support?

**Comment by koden-km** [comment]
Is it possible to add a `make install` option to the Makefile that can install the built version in your current configured grit bin location?

**Comment by koden-km** [comment]
The current Makefile references the **rinq** project?

**Comment by jmalloc** [comment]
Yes it's possible to do that. And yeah I'm just using the `rinq` one for now since it's my most up-to-date Golang makefile.

**Comment by jmalloc** [comment]
"Current configured grit bin location" would have to mean `$(which grit)` which is not ideal.

**Comment by koden-km** [comment]
It could be a setting in the `.grit/config.toml` ?

**Comment by jmalloc** [comment]
I wouldn't want to tie the `Makefile` to anything in there. A regular user of grit, if there were such a thing, wouldn't clone the grit repo at all.
