### ISSUE TITLE
New clone lists many uncommitted changes.

### ISSUE THREAD

**Issue by jmalloc** [jmalloc/grit#41]
I saw this issue on @koden-km's machine when we were playing around with grit clones.

Kev, if you still have it, could you try a `grit rm` on that `grit` clone we made in your $GOPATH and see if it still says there are ~2000 uncommitted changes?

**Comment by koden-km** [comment]
I think i manually deleted it already.

**Comment by jmalloc** [comment]
Kev, have you seen this issue again?

**Comment by koden-km** [comment]
I'm not seeing that issue this time around. I've done a full new setup (grit 0.6.3 on Linux) and haven't noticed any issues. May as well close this now.

**Comment by jmalloc** [comment]
:+1:
