### ISSUE TITLE
Create a custom homebrew tap

### ISSUE THREAD

**Issue by jmalloc** [jmalloc/grit#51]
https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

This would require a build without the `self-update` command.

**Comment by jmalloc** [comment]
/cc @koden-km @parkertr @ezzatron @koshatul @danilvpetrov

Grit can now be [installed via Homebrew](https://github.com/jmalloc/homebrew-grit)! I'd really appreciate if any of you guys could help test it out. It looks to be working fine now but when I was first getting it working it seemed to mangle the binary, producing a `Killed: 9` error message when run.

The archives are still published to the GitHub releases page, so if you run into any trouble it's no problem to revert.  You can also rename your existing `grit` binary and `self-update` will still work as expected, however I would recommend not using `self-update` on the binary installed by `brew`. I will build a separate binary for homebrew that excludes the `self-update` command some time in the future.

**Comment by jmalloc** [comment]
The checksum of the binary (not the release archive) should be as follows:

```console
$ shasum -a 256 $(which grit)
696a38a671cdac0e7eecd165c16dbf9b9bcf967be9d2481aa6aa972d8fce9839  /usr/local/bin/grit
```

**Comment by jmalloc** [comment]
**Important reminder:** If you're using the Grit [shell integration](https://github.com/jmalloc/grit#ok-so-grit-prints-paths-to-the-terminal-i-get-it), the `grit` command you run actually refers to a bash function, not the `grit` binary.

Make sure you're actually getting the one from homebrew in `/usr/local/bin/grit`, both from that `shasum` command above, and from:

```console
$ type grit
grit is a function
grit () 
{ 
    local file="$(mktemp)";
    trap "rm -f '$file'" EXIT;
    "/usr/local/bin/grit" --with-shell-integration="$file" "$@" && source "$file";
    return $?
}
```

You'll need to open a new terminal window (or re-source your `.bash_profile`, etc) to have it regenerate the `grit` bash function using the correct binary.

**Comment by jmalloc** [comment]
@koden-km - I forgot you're a Linux user now! Not sure if you've seen this - https://github.com/Linuxbrew/brew ?  Either way, Grit wont work with that right now, as my "homebrew formula" only describes the Darwin archive, but if you're interested I can try to get it working too.

**Comment by ezzatron** [comment]
I just tried on my home lappy, which did not have an existing grit install. Worked fine, and I got the same checksum. Cool stuff.

**Comment by ezzatron** [comment]
Now I just need your help to do the same for [brew-php](https://github.com/ezzatron/brew-php)!

**Comment by jmalloc** [comment]
Thanks dude! 

It was pretty easy for Grit, because it's a Go binary with no dependencies and I already had it published in an archive via GitHub releases. The trickiest part was was getting the Travis deploy step that updates the Homebrew metadata working (because I had to keep destroying/republishing tags).

Essentially though, when you're using a "custom tap" like I am here, you just need a repo called `homebrew-<name>`. That is, the "tap" `jmalloc/grit` refers to the repo `github.com/jmalloc/homebrew-grit`.

That repo just needs to contain a ruby file which is your "homebrew formula", like [so](https://github.com/jmalloc/homebrew-grit/blob/master/grit.rb). I imagine what will be more difficult for `brew-php` will be specifying the dependencies you have on PHP itself, since the whole point is to make them dynamic.

The [Formula Cookbook](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md) is where I learned what little I know.

**Comment by jmalloc** [comment]
It'd be pretty rad if we could get `brew-php` into the official PHP tap @ https://github.com/Homebrew/homebrew-php

**Comment by jmalloc** [comment]
> ... specifying the dependencies you have on PHP itself ...

Although, I guess it doesn't actually depend on PHP at all.

**Comment by ezzatron** [comment]
Yeah, it's just a single Bash script.

**Comment by jmalloc** [comment]
You could probably do exactly what I'm doing then.

Take a look at [homebrew.sh](https://github.com/jmalloc/grit/blob/master/bin/homebrew.sh) in the main Grit repo. It pushes to the `homebrew-grit` repo after a successful deploy of the archive as an attachment to a Git release from a tag build.

- updated build process to make a `.tgz`
- use `travis setup releases` to configure `.travis.yml` to publish tarball
- add `after_deploy` step that pushes to `ezzatron/homebrew-brew-php`

Probs want to rename it to "superradphpmanager" or something to avoid `brew install brew-php`.

**Comment by jmalloc** [comment]
Oh, you can also put the ruby formula in the same repo under a `homebrew` directory, but I avoided that because I wanted to drive it from tags rather that `master`.

**Comment by ezzatron** [comment]
I think `brew-php` still makes sense as a package name. In order to add a `brew php` command, the bash file has to be an executable called `brew-php` that's placed somewhere in your `$PATH`. Most brew packages that install a single executable are named the same as that executable. Plus there's nothing called `brew-php` currently.

I guess the repo would have to be `ezzatron/homebrew-brew-php`, lol. Is it possible just to rename my existing repo to that and avoid having two?

**Comment by jmalloc** [comment]
Yeah, you don't *need* two, the only reason I decided to keep them separate is so my Travis build can update the homebrew formula on a tag only (ie, tag on `grit` updates `master` on `homebrew-grit`.  

If you don't use tags, you don't even need to rename the repo, just put the formula under a `homebrew` directory in the existing repo and update your Travis build to push an archive to `gh-pages` or something like that.

**Comment by ezzatron** [comment]
Regarding Linux, Travis has a deploy target for [Launchpad](https://docs.travis-ci.com/user/deployment/launchpad/), which would be ideal for Ubuntu and Debian users at least. PPAs function a bit like brew taps for `apt-get`.
