### ISSUE TITLE
Is it possible to have the grit cd list sorted?

### ISSUE THREAD

**Issue by koden-km** [jmalloc/grit#61]
I have a few repo's with the same name for different projects (admin-ui) and when I do `grit cd admin-ui`, the selection list shows but the order is random each time. This might be to do with Go's random map iteration. If the selection list could be sorted by the repo slug then they would always appear in a predicable order.

**Comment by jmalloc** [comment]
Yep, this is `map` iteration order randomisation, due to the fact that the [set of directories](https://github.com/jmalloc/grit/blob/master/src/grit/index/record.go#L30) associated with a slug is stored as a [set](https://github.com/jmalloc/grit/blob/master/src/grit/index/set.go#L3).

**Comment by jmalloc** [comment]
So... I started implementing this then thought I'd do something clever, which is usually a bad idea... but what do you think of [this implementation](https://github.com/jmalloc/grit/compare/61-sort-prompts?expand=1#diff-baaa5e86d31a4f25cab55e765ab662cfR82)?

Basically, it sorts the directories by their "distance" from the current working directory.  That means that if you're in, for example, `rinq/rinq-go` and you `grit cd make`, it'll order `rinq/make` higher than `icecave/make`.

I realise this doesn't match your suggestion exactly, but I *think* it should reduce the number of keystrokes required for the (probably) more common use case of switching to a repo related to the same organisation.

If any two directories are the same distance from cwd, they are sorted by name.  So if you run `grit cd <whatever>` from `~`, you still get consistent ordering.

**Comment by jmalloc** [comment]
Updated the implementation to treat clones that are in a sub-directory of the current working dir as "closer" (lower distance) than clones that are not in a sub-directory of the current working dir.

**Comment by koden-km** [comment]
Searching with distance relative to cwd sounds good.

Only issue i see in your implementation is the spelling in the comment "pathDistsance".
